### ISSUE TITLE
currencyservice: crashloopbackoff 

### ISSUE THREAD

**Issue by agmsb** [GoogleCloudPlatform/microservices-demo#192]
GKE version ` 1.12.5-gke.10`
Istio Add-On Enabled
Deploying release/ kubernetes manifests.

Pod Events.
```
Events:
  Type     Reason     Age                      From                                                     Message
  ----     ------     ----                     ----                                                     -------
  Normal   Scheduled  52s                      default-scheduler                                        Successfully assigned default/currencyservice-78897c6645-6lqp7 to gke-east-cloudville-default-pool-2039bcca-69ld
  Normal   Pulled     50s                      kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Container image "gcr.io/gke-release/istio/proxy_init:1.0.3-gke.3" already present on machine
  Normal   Created    50s                      kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Created container
  Normal   Started    50s                      kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Started container
  Normal   Pulled     43s                      kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Container image "docker.io/istio/proxyv2:1.0.3" already present on machine
  Normal   Created    43s                      kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Created container
  Normal   Started    42s                      kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Started container
  Normal   Pulled     1s (x3 over 45s)         kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Successfully pulled image "gcr.io/google-samples/microservices-demo/currencyservice:v0.1.0"
  Normal   Created    1s (x3 over 43s)         kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Created container
  Normal   Started    1s (x3 over 43s)         kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Started container
  Normal   Pulling    1s (x3 over 49s)         kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  pulling image "gcr.io/google-samples/microservices-demo/currencyservice:v0.1.0"
  Warning  BackOff    <invalid> (x3 over 22s)  kubelet, gke-east-cloudville-default-pool-2039bcca-69ld  Back-off restarting failed container
```
Displayed in FE.
```
rpc error: code = Unavailable desc = no healthy upstream
could not retrieve currencies
main.(*frontendServer).homeHandler
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/handlers.go:47
main.(*frontendServer).(main.homeHandler)-fm
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/main.go:123
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1947
github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/github.com/gorilla/mux/mux.go:162
main.(*logHandler).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/middleware.go:81
main.ensureSessionID.func1
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/middleware.go:103
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1947
github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP
	/go/src/github.com/GoogleCloudPlatform/microservices-demo/src/frontend/vendor/go.opencensus.io/plugin/ochttp/server.go:82
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2697
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1830
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2361
```

**Comment by agmsb** [comment]
digging through the logs and seeing this:

```
{
 insertId:  "sw1nhtleundb3pwvs"  
 logName:  "projects/csp-city/logs/stderr"  
 receiveTimestamp:  "2019-03-13T22:46:24.870580296Z"  
 resource: {
  labels: {…}   
  type:  "k8s_container"   
 }
 severity:  "ERROR"  
 textPayload:  "TypeError: Cannot read property 'Cube' of null
    at xml2js.parseString (/usr/src/app/server.js:90:28)
    at Parser.<anonymous> (/usr/src/app/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.exports.Parser.Parser.parseString (/usr/src/app/node_modules/xml2js/lib/parser.js:313:16)
    at Parser.parseString (/usr/src/app/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/usr/src/app/node_modules/xml2js/lib/parser.js:354:19)
    at Request.request [as _callback] (/usr/src/app/server.js:85:14)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
"  
 timestamp:  "2019-03-13T22:46:12.924030460Z"  
}
```

**Comment by ahmetb** [comment]
@agmsb we recently removed the xml stuff from currencyservice, can you please fetch from master? Which commit were you runing?

**Comment by agmsb** [comment]
Thank you @ahmetb. Catching up to master fixed it.

**Comment by michaelsorenson** [comment]
I'm getting this same frontend error, but currencyservice and loadgenerator workloads saying "Does not have minimum availability", and increasing the node pool doesn't seem to fix the issue. My node pool uses 2 vCPUs and 3.5 GB RAM, do I need to increase the RAM?

**Comment by ahmetb** [comment]
@michaelsorenson 

1. please open a new issue, this issue is over.

2. please paste the full error you're seeing, I am not sure which command gave you that message.
