### ISSUE TITLE
emailservice crashlooping

### ISSUE THREAD

**Issue by craigbox** [GoogleCloudPlatform/microservices-demo#255]
Installed on Kubernetes via [mesh expansion example](https://github.com/GoogleCloudPlatform/istio-samples/tree/master/mesh-expansion-gce). All the other services are operating correctly, emailservice is crashlooping.

I set the cluster up without Workload Identity but added it later (enabled it on the cluster and bounced the nodepool to install the agent, [as per the instructions](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity))

```
{"timestamp": 1571526075.3596034, "severity": "INFO", "name": "emailservice-server", "message": "starting the email service in dummy mode."}
{"timestamp": 1571526075.3601294, "severity": "INFO", "name": "emailservice-server", "message": "Skipping Stackdriver Profiler Python agent initialization. Set environment variable ENABLE_PROFILER=1 to enable."}
INFO:emailservice-server:starting the email service in dummy mode.
INFO:emailservice-server:Skipping Stackdriver Profiler Python agent initialization. Set environment variable ENABLE_PROFILER=1 to enable.
INFO:emailservice-server:listening on port: 8080
{"timestamp": 1571526075.44175, "severity": "INFO", "name": "emailservice-server", "message": "listening on port: 8080"}
ERROR:grpc._server:Exception calling application: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
	debug_error_string = "{"created":"@1571526076.651824820","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/ext/grpc/server_interceptor.py", line 85, in new_behavior
    execution_context.get_opencensus_tracer().end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracer.py", line 117, in end_span
    self.tracer.end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracers/context_tracer.py", line 123, in end_span
    self.exporter.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 234, in export
    self.transport.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/transports/sync.py", line 23, in export
    self.exporter.emit(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 225, in emit
    self.client.batch_write_spans(project, stackdriver_spans)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 100, in batch_write_spans
    name=name, spans=spans, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/_gapic.py", line 89, in batch_write_spans
    name=name, spans=spans_pb_list, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 256, in batch_write_spans
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unauthenticated: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
ERROR:grpc._server:Exception calling application: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
	debug_error_string = "{"created":"@1571526076.743373515","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/ext/grpc/server_interceptor.py", line 85, in new_behavior
    execution_context.get_opencensus_tracer().end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracer.py", line 117, in end_span
    self.tracer.end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracers/context_tracer.py", line 123, in end_span
    self.exporter.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 234, in export
    self.transport.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/transports/sync.py", line 23, in export
    self.exporter.emit(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 225, in emit
    self.client.batch_write_spans(project, stackdriver_spans)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 100, in batch_write_spans
    name=name, spans=spans, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/_gapic.py", line 89, in batch_write_spans
    name=name, spans=spans_pb_list, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 256, in batch_write_spans
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unauthenticated: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
ERROR:grpc._server:Exception calling application: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
	debug_error_string = "{"created":"@1571526080.860304954","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/ext/grpc/server_interceptor.py", line 85, in new_behavior
    execution_context.get_opencensus_tracer().end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracer.py", line 117, in end_span
    self.tracer.end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracers/context_tracer.py", line 123, in end_span
    self.exporter.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 234, in export
    self.transport.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/transports/sync.py", line 23, in export
    self.exporter.emit(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 225, in emit
    self.client.batch_write_spans(project, stackdriver_spans)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 100, in batch_write_spans
    name=name, spans=spans, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/_gapic.py", line 89, in batch_write_spans
    name=name, spans=spans_pb_list, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 256, in batch_write_spans
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unauthenticated: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
ERROR:grpc._server:Exception calling application: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
	debug_error_string = "{"created":"@1571526081.140930873","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/ext/grpc/server_interceptor.py", line 85, in new_behavior
    execution_context.get_opencensus_tracer().end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracer.py", line 117, in end_span
    self.tracer.end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracers/context_tracer.py", line 123, in end_span
    self.exporter.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 234, in export
    self.transport.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/transports/sync.py", line 23, in export
    self.exporter.emit(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 225, in emit
    self.client.batch_write_spans(project, stackdriver_spans)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 100, in batch_write_spans
    name=name, spans=spans, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/_gapic.py", line 89, in batch_write_spans
    name=name, spans=spans_pb_list, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 256, in batch_write_spans
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unauthenticated: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
ERROR:grpc._server:Exception calling application: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
	debug_error_string = "{"created":"@1571526085.953478041","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/ext/grpc/server_interceptor.py", line 85, in new_behavior
    execution_context.get_opencensus_tracer().end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracer.py", line 117, in end_span
    self.tracer.end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracers/context_tracer.py", line 123, in end_span
    self.exporter.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 234, in export
    self.transport.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/transports/sync.py", line 23, in export
    self.exporter.emit(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 225, in emit
    self.client.batch_write_spans(project, stackdriver_spans)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 100, in batch_write_spans
    name=name, spans=spans, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/_gapic.py", line 89, in batch_write_spans
    name=name, spans=spans_pb_list, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 256, in batch_write_spans
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unauthenticated: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
ERROR:grpc._server:Exception calling application: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
	debug_error_string = "{"created":"@1571526086.148386809","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/ext/grpc/server_interceptor.py", line 85, in new_behavior
    execution_context.get_opencensus_tracer().end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracer.py", line 117, in end_span
    self.tracer.end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracers/context_tracer.py", line 123, in end_span
    self.exporter.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 234, in export
    self.transport.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/transports/sync.py", line 23, in export
    self.exporter.emit(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 225, in emit
    self.client.batch_write_spans(project, stackdriver_spans)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 100, in batch_write_spans
    name=name, spans=spans, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/_gapic.py", line 89, in batch_write_spans
    name=name, spans=spans_pb_list, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 256, in batch_write_spans
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unauthenticated: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
ERROR:grpc._server:Exception calling application: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAUTHENTICATED
	details = "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
	debug_error_string = "{"created":"@1571526090.846417037","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","grpc_status":16}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/ext/grpc/server_interceptor.py", line 85, in new_behavior
    execution_context.get_opencensus_tracer().end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracer.py", line 117, in end_span
    self.tracer.end_span()
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/tracers/context_tracer.py", line 123, in end_span
    self.exporter.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 234, in export
    self.transport.export(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/transports/sync.py", line 23, in export
    self.exporter.emit(span_datas)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 225, in emit
    self.client.batch_write_spans(project, stackdriver_spans)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 100, in batch_write_spans
    name=name, spans=spans, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/_gapic.py", line 89, in batch_write_spans
    name=name, spans=spans_pb_list, retry=retry, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 256, in batch_write_spans
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unauthenticated: 401 Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

```

**Comment by ahmetb** [comment]
Seems to be a node scopes/permissions issue regardless. I doubt there’s much this repo can do. cc: @askmeegs

**Comment by EvertonSA** [comment]
I just want to comment that I'm also facing this situation with a GKE raw 1.3 Istio instalation

**Comment by askmeegs** [comment]
@DanSanche if possible, could you look into this?  Connecting to stackdriver is throwing a 401 when  a GKE cluster has workload identity enabled.

**Comment by DanSanche** [comment]
Hmm, I haven't been able to reproduce this

@craigbox Did you enable workload identity before deploying hipstershop? Did you do anything else outside the [mesh expansion instructions](https://github.com/GoogleCloudPlatform/istio-samples/tree/master/mesh-expansion-gce)? Do you know which version of istio you were using?

**Comment by askmeegs** [comment]
@DanSanche have you tried in a GKE cluster with workload identity enabled? or a Kops cluster in GCE?

**Comment by DanSanche** [comment]
I was using a GKE cluster. I haven't tried kops

**Comment by craigbox** [comment]
> Did you enable workload identity before deploying hipstershop? 

yes

> Did you do anything else outside the mesh expansion instructions? 

No, and I don't think that anything to do with that should be relevant.

> Do you know which version of istio you were using?

1.3.3

**Comment by DanSanche** [comment]
I threw together [this script](https://paste.googleplex.com/5987376734142464) to document the steps I took to set up the environment. Let me know if anything stands out

**Comment by ahmed1smael** [comment]
I am running into the same issue with workload identity enabled. Its work mentioning that I enabled the feature on existing cluster.

**Comment by ahmetb** [comment]
In case of GKE workload identity enabled, we expect the identity has permissions to be able to send metrics, traces etc, but this should not be required.

In lack of these permissions, the `emailservice` should not be crashing (simply because it doesn't crash on `minikube` or similar when you run it with no credentials at all). Any further investigation is appreciated.

**Comment by tangiel** [comment]
I'm getting the same issue on occasion with both emailservice and frontend. I discovered that, at least in the case of frontend, the log messages don't seem to directly correspond to the task exit. In one invocation loop, the last log timestamp is at 23:30:56, but docker shows the exit time is 23:31:07, so almost 10 seconds elapse before the process actually exits. I've been trying to see what could exit the task with no fatal log message and an exit code of 2, but have come up empty handed so far.

**Comment by tangiel** [comment]
Ok, turns out my issue is separate and stems from not reading the Istio instructions in README, which says that I need to delete some health checks due to MTLS interference.
