### ISSUE TITLE
Emailservice is failing on a non-GKE cluster

### ISSUE THREAD

**Issue by huikang** [GoogleCloudPlatform/microservices-demo#316]
Is there a way to disable the use of GOOGLE_APPLICATION_CREDENTIALS so that the app can be deployed in a non-GKE cluster? Thanks.

```
{"timestamp": 1585492106.3320029, "severity": "INFO", "name": "emailservice-server", "message": "starting the email service in dummy mode."}
{"timestamp": 1585492106.3322504, "severity": "INFO", "name": "emailservice-server", "message": "Profiler disabled."}
{"timestamp": 1585492106.3323855, "severity": "INFO", "name": "emailservice-server", "message": "Tracing enabled."}
Traceback (most recent call last):
  File "email_server.py", line 190, in <module>
    transport=AsyncTransport)
  File "/usr/local/lib/python3.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 199, in __init__
    client = Client(project=project_id)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/trace/client.py", line 43, in __init__
    super(Client, self).__init__(project=project, credentials=credentials)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 223, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 175, in __init__
    project = self._determine_default(project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/client.py", line 190, in _determine_default
    return _determine_default_project(project)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/usr/local/lib/python3.7/site-packages/google/auth/_default.py", line 306, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**Comment by huikang** [comment]
Seeing similar error for recommendation servier

```
{"timestamp": 1585492246.453169, "severity": "INFO", "name": "recommendationservice-server", "message": "initializing recommendationservice"}
{"timestamp": 1585492246.45359, "severity": "INFO", "name": "recommendationservice-server", "message": "Profiler enabled."}
{"timestamp": 1585492249.475446, "severity": "INFO", "name": "recommendationservice-server", "message": "Unable to start Stackdriver Profiler Python agent. Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started"}
{"timestamp": 1585492249.475925, "severity": "INFO", "name": "recommendationservice-server", "message": "Sleeping 10 seconds to retry Stackdriver Profiler agent initialization"}
{"timestamp": 1585492253.495484, "severity": "INFO", "name": "recommendationservice-server", "message": "Unable to start Stackdriver Profiler Python agent. Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started"}
{"timestamp": 1585492253.495809, "severity": "INFO", "name": "recommendationservice-server", "message": "Sleeping 20 seconds to retry Stackdriver Profiler agent initialization"}
{"timestamp": 1585492257.502488, "severity": "INFO", "name": "recommendationservice-server", "message": "Unable to start Stackdriver Profiler Python agent. Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started"}
{"timestamp": 1585492257.502791, "severity": "INFO", "name": "recommendationservice-server", "message": "Sleeping 30 seconds to retry Stackdriver Profiler agent initialization"}
{"timestamp": 1585492258.504088, "severity": "INFO", "name": "recommendationservice-server", "message": "Tracing enabled."}
Traceback (most recent call last):
  File "/recommendationservice/recommendation_server.py", line 109, in <module>
    transport=AsyncTransport)
  File "/usr/local/lib/python2.7/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 199, in __init__
    client = Client(project=project_id)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/trace/client.py", line 43, in __init__
    super(Client, self).__init__(project=project, credentials=credentials)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/client.py", line 223, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/client.py", line 175, in __init__
    project = self._determine_default(project)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/client.py", line 190, in _determine_default
    return _determine_default_project(project)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/usr/local/lib/python2.7/site-packages/google/auth/_default.py", line 306, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

```

**Comment by plachira** [comment]
Uncomment following variables in kubernetes-manifests

 ```
 - name: DISABLE_TRACING
    value: "1"
- name: DISABLE_PROFILER
   value: "1"
```

**Comment by ahmetb** [comment]
Technically should not be needed but we’ll investigate, others have hit this, too.

**Comment by nikos9742** [comment]
@plachira Unfortunately this doesn't work. I'm diving in the code to find which env variable need to be used to correctly disable tracing and profiler.

**Comment by huikang** [comment]
@nikos9742 , fyi, uncommenting tracing and profiler work for me.

**Comment by nikos9742** [comment]
@huikang Depending on the installation method it seems that i need to changes those values at diffferents paths

**Comment by DanSanche** [comment]
I'm looking into this now
