### ISSUE TITLE
recommendationservice in CrashLoopBackoff

### ISSUE THREAD

**Issue by shreyasHpandya** [GoogleCloudPlatform/microservices-demo#501]
I am trying to run in minikube, I don't have GCP account, Is GCP required for this service?

I deployed from `release` directory with `kubectl apply -f kubernetes-manifests.yaml`

Traceback
        
  ```
      Traceback (most recent call last):                                                                                                                                                          │
│   File "/recommendationservice/recommendation_server.py", line 125, in <module>                                                                                                             │
│     version='1.0.0'                                                                                                                                                                         │
│   File "/usr/local/lib/python2.7/site-packages/googleclouddebugger/__init__.py", line 152, in enable                                                                                        │
│     _StartDebugger()                                                                                                                                                                        │
│   File "/usr/local/lib/python2.7/site-packages/googleclouddebugger/__init__.py", line 72, in _StartDebugger                                                                                 │
│     _flags.get('service_account_json_file'))                                                                                                                                                │
│   File "/usr/local/lib/python2.7/site-packages/googleclouddebugger/gcp_hub_client.py", line 207, in SetupAuth                                                                               │
│     scopes=_CLOUD_PLATFORM_SCOPE)                                                                                                                                                           │
│   File "/usr/local/lib/python2.7/site-packages/google/auth/_default.py", line 306, in default                                                                                               │
│     raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)                                                                                                                                 │
│ DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more inf │
│ {"timestamp": 1612879277.281563, "severity": "ERROR", "name": "recommendationservice-server", "message": "None"}  
```

**Comment by mathieu-benoit** [comment]
Hi @shreyasHpandya, please see this thread and workaround for you for this specific issue you are describing: https://github.com/GoogleCloudPlatform/microservices-demo/issues/457#issuecomment-741928978. Furthermore, like explained in there, it will not be an issue anymore in the future release/version of that `recommendationservice` container.

Closing this for now, but feel free to reopen it if the workaround is not resolving your issue. Thanks!
