### ISSUE TITLE
Cartservice failing on skaffold run 

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/microservices-demo#561]
Happening both locally and on the latest master branch deploy tests. 

```
+ cartservice-6df59b7fc-dg84z › server
cartservice-6df59b7fc-dg84z server Connecting to Redis: redis-cart:6379,ssl=false,allowAdmin=true,connectRetry=5
cartservice-6df59b7fc-dg84z server Unhandled exception. StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on redis-cart:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 180s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 7s ago, v: 2.2.4.27433
cartservice-6df59b7fc-dg84z server    at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log)
cartservice-6df59b7fc-dg84z server    at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log)
cartservice-6df59b7fc-dg84z server    at cartservice.cartstore.RedisCartStore.EnsureRedisConnected()
cartservice-6df59b7fc-dg84z server    at cartservice.cartstore.RedisCartStore.InitializeAsync()
cartservice-6df59b7fc-dg84z server    at cartservice.Startup.ConfigureServices(IServiceCollection services)
cartservice-6df59b7fc-dg84z server    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
cartservice-6df59b7fc-dg84z server    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
cartservice-6df59b7fc-dg84z server    at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters)
cartservice-6df59b7fc-dg84z server    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
cartservice-6df59b7fc-dg84z server    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
cartservice-6df59b7fc-dg84z server    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
cartservice-6df59b7fc-dg84z server    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
cartservice-6df59b7fc-dg84z server    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
cartservice-6df59b7fc-dg84z server    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
cartservice-6df59b7fc-dg84z server    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
cartservice-6df59b7fc-dg84z server    at Microsoft.Extensions.Hosting.HostBuilder.Build()
cartservice-6df59b7fc-dg84z server    at <Program>$.<Main>$(String[] args)
- cartservice-6df59b7fc-dg84z › server
+ cartservice-6df59b7fc-dg84z › server
```

neither of the last two PRs modified cartservice or redis.

**Comment by askmeegs** [comment]
Update - after running the latest master commit locally a few times w/ skaffold dev, it doesn't fail every time. sometimes cartservice recovers -- 

```
cartservice-57c4c9898c-5m4sd server       Error reading message.
cartservice-57c4c9898c-5m4sd server       System.IO.IOException: The request stream was aborted.
cartservice-57c4c9898c-5m4sd server        ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
cartservice-57c4c9898c-5m4sd server          --- End of inner exception stack trace ---
cartservice-57c4c9898c-5m4sd server          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.ReadAsync(CancellationToken cancellationToken)
cartservice-57c4c9898c-5m4sd server          at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
cartservice-57c4c9898c-5m4sd server fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
cartservice-57c4c9898c-5m4sd server       Error when executing service method 'Check'.
cartservice-57c4c9898c-5m4sd server       System.IO.IOException: The request stream was aborted.
cartservice-57c4c9898c-5m4sd server        ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
cartservice-57c4c9898c-5m4sd server          --- End of inner exception stack trace ---
cartservice-57c4c9898c-5m4sd server          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.ReadAsync(CancellationToken cancellationToken)
cartservice-57c4c9898c-5m4sd server          at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
cartservice-57c4c9898c-5m4sd server          at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
cartservice-57c4c9898c-5m4sd server          at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
cartservice-57c4c9898c-5m4sd server Checking CartService Health
cartservice-57c4c9898c-5m4sd server Checking CartService Health
cartservice-57c4c9898c-5m4sd server Checking CartService Health
cartservice-57c4c9898c-5m4sd server Checking CartService Health
cartservice-57c4c9898c-5m4sd server Checking CartService Health
cartservice-57c4c9898c-5m4sd server Checking CartService Health
cartservice-57c4c9898c-5m4sd server GetCartAsync called with userId=46fb6613-11c6-43a2-8094-e8e4cce31697
cartservice-57c4c9898c-5m4sd server EmptyCartAsync called with userId=46fb6613-11c6-43a2-8094-e8e4cce31697
```

**Comment by askmeegs** [comment]
Re-running the master build, now the pods start up successfully but the smoke test is failing because the loadgen is throwing 9 errors -- 

<img width="621" alt="Screen Shot 2021-06-20 at 12 21 32 PM" src="https://user-images.githubusercontent.com/3137106/122681394-246e4880-d1c2-11eb-8892-40ff5388616c.png">

**Comment by niryarden** [comment]
suffering from the same issue, tried to run with [this branch](https://github.com/GoogleCloudPlatform/microservices-demo/pull/562) and it does not seem to fix it ☹️
just running `skaffold dev` again and again until it works

**Comment by NimJay** [comment]
## My Investigation Updates
Just adding some findings and thoughts from my investigation:
* I was, fortunately, able to reproduce today on the master branch (47c5f102b7bc81b0e88b948f143a0500eb66692b).
* I used `skaffold dev --default-repo=gcr.io/nimjay-microservices-demo` 5 times, and it failed 3 times with the following error:
```
Connecting to Redis: redis-cart:6379,ssl=false,allowAdmin=true,connectRetry=5,abortConnect=false
      > [cartservice-8d9dbdd5d-7g4cg server] Wasn't able to connect to redis
      > [cartservice-8d9dbdd5d-7g4cg server] Unhandled exception. System.ApplicationException: Wasn't able to connect to redis
      > [cartservice-8d9dbdd5d-7g4cg server]    at cartservice.cartstore.RedisCartStore.EnsureRedisConnected()
``` 
*  My guess right now is the fact that we're simply [using the `redis:alpine` image](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/kubernetes-manifests/redis.yaml#L30) without specifying the version caused things to break. Maybe newer versions of `redis:apline` take a bit longer to boot? 
* The reason for the "random" nature of this bug might be due to the randomness in [Redis's `ExponentialRetry` policy](https://stackexchange.github.io/StackExchange.Redis/Configuration#reconnectretrypolicy).
* We _could_ use [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#using-init-containers) to make Kubernetes wait for the Redis pod to be ready before deploying the `cartservice` pod, but there are [folks that advise against this](https://stackoverflow.com/questions/51079849/kubernetes-wait-for-other-pod-to-be-ready/51080978#51080978). Even though Kubernetes [lists this use of init containers as a valid use](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#using-init-containers), I think it might be too hacky — especially for a demo app.
  * Similar to [Nir's solution](https://github.com/Rookout/microservices-demo/pull/4/files#diff-e1927d7f37ae042f609e2179e06d9e6b8b4007df2f8b205f83f186e4c2b498b0), I think the `cartservice` should be responsible for retrying the Redis connection.
* We might be able to solve this issue by providing a better configuration for Redis's [`ReconnectRetryPolicy`](https://stackexchange.github.io/StackExchange.Redis/Configuration#reconnectretrypolicy).
* I will resume the investigation...
