### ISSUE TITLE
CartService keep on crashing

### ISSUE THREAD

**Issue by Jayashankara-DM-135** [GoogleCloudPlatform/microservices-demo#586]
Issue: Cart service is unable to connect to Redis server even those Redis is up and running.

Setup: I am running on-prem kubernetes cluster using kubeadm

Logs:
=================== 
$ sudo kubectl logs cartservice-76c7dcdf79-ft4sl
sudo: unable to resolve host k8s-master-node: Connection timed out
**_Connecting to Redis: redis-cart:6379,ssl=false,allowAdmin=true,abortConnect=false
Wasn't able to connect to redis_**
Unhandled exception. System.ApplicationException: Wasn't able to connect to redis
   at cartservice.cartstore.RedisCartStore.EnsureRedisConnected()
   at cartservice.cartstore.RedisCartStore.InitializeAsync()
   at cartservice.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at <Program>$.<Main>$(String[] args)

$ sudo kubectl get pod
sudo: unable to resolve host k8s-master-node
NAME                                     READY   STATUS    RESTARTS   AGE
adservice-5c856f9f4c-kwwcf               1/1     Running   0          18m
**cartservice-76c7dcdf79-ft4sl             0/1     Error     5          18m**
checkoutservice-84849dc7ff-wlntc         1/1     Running   0          18m
currencyservice-7d5b7fc64f-zd5j2         1/1     Running   0          18m
emailservice-577486bcbc-khsx4            1/1     Running   0          18m
frontend-846b864fc-zxlqp                 1/1     Running   0          18m
loadgenerator-589648f87f-jqpfs           1/1     Running   0          18m
paymentservice-65bdf6757d-2nwzm          1/1     Running   0          18m
productcatalogservice-567ffd84b5-h2d5g   1/1     Running   0          18m
recommendationservice-7dc584f8d5-5dp2r   1/1     Running   0          18m
redis-cart-85478974d5-qxc55              1/1     Running   0          18m
shippingservice-f65794ddc-6prxr          1/1     Running   0          18m

**Comment by Jayashankara-DM-135** [comment]
$ sudo kubectl logs redis-cart-85478974d5-qxc55
sudo: unable to resolve host k8s-master-node
1:C 07 Aug 2021 12:21:02.523 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 Aug 2021 12:21:02.523 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 Aug 2021 12:21:02.523 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 07 Aug 2021 12:21:02.524 * monotonic clock: POSIX clock_gettime
1:M 07 Aug 2021 12:21:02.525 * Running mode=standalone, port=6379.
1:M 07 Aug 2021 12:21:02.525 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 07 Aug 2021 12:21:02.525 # Server initialized

$ 

When I am trying to access the front end, I got below error on web-browser.

rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup currencyservice on 10.96.0.10:53: read udp 192.168.148.148:37152->10.96.0.10:53: i/o timeout"
could not retrieve currencies
main.(*frontendServer).homeHandler
	/src/handlers.go:58
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212
main.(*logHandler).ServeHTTP
	/src/middleware.go:81
main.ensureSessionID.func1
	/src/middleware.go:103
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP
	/go/pkg/mod/go.opencensus.io@v0.21.0/plugin/ochttp/server.go:86
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1925
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by Jayashankara-DM-135** [comment]
I am running on-prem kubernetes cluster using kubeadm

**Comment by ahmetb** [comment]
Same with #585, you have issues in your cluster. This time the networking seems to be the problem. I highly doubt it has anything to do with the demo.

I recommend you get a Kubernetes cluster in a good shape first.

**Comment by Jayashankara-DM-135** [comment]
I am able to access the redis-cart pod  form outside. Not sure why CartService is not able access. Can you please suggest what could the reason and some debugging steps to figure it out
