### ISSUE TITLE
Multiple services crashing out of the box due to missing credentials (local cluster)

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/microservices-demo#663]
Once I applied the release/kubernetes-manifests.yaml to a local cluster (kind, running kubernetes 1.23.0) I notice that a few pods are crashing, with logs indicating that either "project ID not set" or "cannot initialize credentials".

In earlier versions of this demo app, it worked both locally and on GCP without having to configure anything (such as adjusting the environment variables), and that was one of the principles we wanted to keep per go/microservices-demo doc. I recommend restoring that behavior as it's useful to first-time users.

paymentservice (CrashLoopBackOff)
```
 kubectl logs -f paymentservice-54b7545694-6rjwv
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
{"severity":"info","time":1639616190938,"pid":1,"hostname":"paymentservice-54b7545694-6rjwv","name":"paymentservice-server","message":"PaymentService gRPC server started on port 50051","v":1}
/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120
        throw new Error('Project ID must be specified in the configuration');
              ^

Error: Project ID must be specified in the configuration
    at initConfigMetadata (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createProfiler (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:158:26)
    at async Object.start (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:182:22)
```

shippingservice (CrashLoopBackOff)

```
{"message":"Tracing enabled.","severity":"info","timestamp":"2021-12-16T00:57:44.94692172Z"}
{"message":"Profiling enabled.","severity":"info","timestamp":"2021-12-16T00:57:44.946979558Z"}
{"message":"jaeger initialization disabled.","severity":"info","timestamp":"2021-12-16T00:57:44.947065127Z"}
{"message":"Stats enabled.","severity":"info","timestamp":"2021-12-16T00:57:44.94706558Z"}
{"message":"Shipping Service listening on port :50051","severity":"info","timestamp":"2021-12-16T00:57:44.947360261Z"}
{"message":"failed to initialize Stackdriver exporter: stackdriver: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.","severity":"warning","timestamp":"2021-12-16T00:57:44.948239335Z"}
{"message":"sleeping 10s to retry initializing Stackdriver exporter","severity":"info","timestamp":"2021-12-16T00:57:44.948266195Z"}
{"message":"failed to start profiler: project ID must be specified in the configuration if running outside of GCP","severity":"warning","timestamp":"2021-12-16T00:57:44.948276815Z"}
{"message":"sleeping 10s to retry initializing Stackdriver profiler","severity":"info","timestamp":"2021-12-16T00:57:44.948283437Z"}
{"message":"failed to start profiler: project ID must be specified in the configuration if running outside of GCP","severity":"warning","timestamp":"2021-12-16T00:57:54.948410021Z"}
{"message":"sleeping 20s to retry initializing Stackdriver profiler","severity":"info","timestamp":"2021-12-16T00:57:54.948468961Z"}
{"message":"failed to initialize Stackdriver exporter: stackdriver: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.","severity":"warning","timestamp":"2021-12-16T00:57:54.948444596Z"}
{"message":"sleeping 20s to retry initializing Stackdriver exporter","severity":"info","timestamp":"2021-12-16T00:57:54.948480152Z"}
```

currencyservice (CrashLoopBackOff)

```
Profiler enabled.
Tracing enabled.
Debugger enabled.
{"severity":"info","time":1639616372847,"pid":1,"hostname":"currencyservice-68b9dd7dcb-nc4fh","name":"currencyservice-server","message":"Starting gRPC server on port 7000...","v":1}
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{"severity":"info","time":1639616372944,"pid":1,"hostname":"currencyservice-68b9dd7dcb-nc4fh","name":"currencyservice-server","message":"CurrencyService gRPC server started on port 7000","v":1}
/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120
        throw new Error('Project ID must be specified in the configuration');
              ^

Error: Project ID must be specified in the configuration
    at initConfigMetadata (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createProfiler (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:158:26)
    at async Object.start (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:182:22)
```

**Comment by askmeegs** [comment]
This bug was fixed by #665  and the updated YAML files will be in the next release.
