### ISSUE TITLE
cut a new 0.3.5 release from main, please

### ISSUE THREAD

**Issue by prune998** [GoogleCloudPlatform/microservices-demo#681]
### Describe the bug 
Some services (Payment, for sure) does not have options to disable google-specific tracing/profiler. Payment service is crashing if the cluster is not in GCP.

### To Reproduce 
start Payment service in a K8s cluster not on GCP

### Logs  
```
/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120
        throw new Error('Project ID must be specified in the configuration');
              ^

Error: Project ID must be specified in the configuration
    at initConfigMetadata (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async createProfiler (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:158:26)
    at async Object.start (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:182:22)
```

### Environment 
EKS cluster

### Additional context 
The code is already changed in the repo, you only need to cut a new release and rebuild the docker images

### Exposure 
bug is persistent and widespread

**Comment by NimJay** [comment]
We've just created a new release (`0.3.5`).
So I'm closing this issue.
Thanks for creating this issue, @prune998! :)

**Comment by prune998** [comment]
thanks @NimJay !
