### ISSUE TITLE
Missing libcrypt dependency in adservice

### ISSUE THREAD

**Issue by rvrignaud** [GoogleCloudPlatform/microservices-demo#89]
When starting up, adservice throw a large stacktrace with what seems to be a missing libcrypt dependency:
```
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:93)
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:561)
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:554)
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:489)
        at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:337)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:405)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:206)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:157)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:149)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:151)
        at com.google.cloud.trace.v2.stub.GrpcTraceServiceStub.create(GrpcTraceServiceStub.java:70)
        at com.google.cloud.trace.v2.stub.TraceServiceStubSettings.createStub(TraceServiceStubSettings.java:99)
        at com.google.cloud.trace.v2.TraceServiceClient.<init>(TraceServiceClient.java:137)
        at com.google.cloud.trace.v2.TraceServiceClient.create(TraceServiceClient.java:118)
        at io.opencensus.exporter.trace.stackdriver.StackdriverV2ExporterHandler.createWithCredentials(StackdriverV2ExporterHandler.java:160)
        at io.opencensus.exporter.trace.stackdriver.StackdriverTraceExporter.createAndRegister(StackdriverTraceExporter.java:87)
        at hipstershop.AdService.initStackdriver(AdService.java:214)
        at hipstershop.AdService$2.run(AdService.java:244)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_646356280454963582202.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libnetty_tcnative_linux_x86_646356280454963582202.so)
                at java.lang.ClassLoader$NativeLibrary.load(Native Method)
                at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
                at java.lang.Runtime.load0(Runtime.java:809)
                at java.lang.System.load(System.java:1086)
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:243)
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:187)
                at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:85)
                ... 23 more
```

**Comment by ahmetb** [comment]
Thanks for bringing this up. I wonder why we didn't catch this before. Did you do anything special to trigger it or doesn't even load at all?

Did adding the missing dependency work?

**Comment by rvrignaud** [comment]
The only thing I did different from the readme is to enable debugger scope in the cluster. Not tested that theory but maybe this only shows up when debugger register itself.

**Comment by ahmetb** [comment]
cc: @orthros

**Comment by ahmetb** [comment]
Looks like it's coming from the stackdriver tracing stack, it explains why we didn't catch this during local testing while migrating to smaller alpine base images.
